### ISSUE TITLE
JSON wordt dubbel opgehaald

### ISSUE THREAD

**Issue by LeroyAndrade** [LeroyAndrade/BOEKJson-xmlHttp#2]
Beste heer den Blanken,

Probleem #2: is dat JSON data dubbel wordt weergeven op index.html -->https://github.com/LeroyAndrade/BOEKJson-xmlHttp/blob/0133fc3b29a541eccd453162dbae3448622a2eba/js/sorteerBoeken.js#L129

Als ik mij niet vergis, is de vraag om zelf het probleem te kunnen oplossen, welke breakpoint ik naar moet luisteren, zoja welke?

Met vriendelijke groet,
Leroy Andrade

**Comment by Theo-denBlanken** [comment]
Er worden auteurs uitgevoerd.
Je kunt dan ook een extra stringkarakter toevoegen.
Ik zie namelijk dat er een auteur wordt toegevoegd in de tabel r132 en in regel 140 nog eens.

**Comment by Theo-denBlanken** [comment]
Probeer in jouw code wat orde aan te brengen. Als je iets uitgeprobeerd hebt en daar ben je tevreden over, verwijder dan de oude code. Dan jou je het overzicht.

**Comment by LeroyAndrade** [comment]
Commentaar doorgenomen en code aangepast en wijziging doorgevoerd: 
- declaratie van object.methode zodat data niet dubbel wordt getoond.

**Comment by LeroyAndrade** [comment]
Commentaar doorgenomen en code aangepast en wijziging doorgevoerd:

-declaratie van object.methode zodat data niet dubbel wordt getoond.
-comments van oude code -> overgezet naar privé folder en u een meer overzichterlijke gegeven.
